"""Contratos de persistencia para Instagram."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    InstagramAccount,
    InstagramCaptionVersion,
    InstagramConnection,
    InstagramContentLink,
    InstagramCoverVersion,
    InstagramCarouselChild,
    InstagramInsightImport,
    InstagramInsightValue,
    InstagramRateLimitUsage,
    InstagramRemoteMedia,
    InstagramSyncItem,
    InstagramSyncReport,
    InstagramSyncRun,
    InstagramSyncSchedule,
)


class InstagramIntegrationRepository(Protocol):
    def upsert_connection(self, connection: InstagramConnection) -> InstagramConnection: ...
    def get_connection(self, connection_id: str) -> InstagramConnection | None: ...
    def list_connections(self, creator_id: str) -> list[InstagramConnection]: ...

    def upsert_account(self, account: InstagramAccount) -> InstagramAccount: ...
    def get_account(self, account_id: str) -> InstagramAccount | None: ...
    def get_account_by_instagram_user_id(self, creator_id: str, instagram_user_id: str) -> InstagramAccount | None: ...
    def list_accounts(self, creator_id: str, *, connection_id: str | None = None) -> list[InstagramAccount]: ...

    def upsert_remote_media(self, media: InstagramRemoteMedia) -> InstagramRemoteMedia: ...
    def get_remote_media(self, remote_media_id: str) -> InstagramRemoteMedia | None: ...
    def get_remote_media_by_instagram_id(self, creator_id: str, instagram_media_id: str) -> InstagramRemoteMedia | None: ...
    def list_remote_media(self, creator_id: str, *, account_id: str | None = None) -> list[InstagramRemoteMedia]: ...

    def upsert_carousel_child(self, child: InstagramCarouselChild) -> InstagramCarouselChild: ...
    def list_carousel_children(self, remote_media_id: str) -> list[InstagramCarouselChild]: ...

    def upsert_caption_version(self, caption: InstagramCaptionVersion) -> InstagramCaptionVersion: ...
    def list_caption_versions(self, remote_media_id: str) -> list[InstagramCaptionVersion]: ...

    def upsert_cover_version(self, cover: InstagramCoverVersion) -> InstagramCoverVersion: ...
    def list_cover_versions(self, remote_media_id: str) -> list[InstagramCoverVersion]: ...

    def upsert_sync_run(self, run: InstagramSyncRun) -> InstagramSyncRun: ...
    def get_sync_run(self, run_id: str) -> InstagramSyncRun | None: ...
    def list_sync_runs(self, creator_id: str) -> list[InstagramSyncRun]: ...

    def upsert_sync_item(self, item: InstagramSyncItem) -> InstagramSyncItem: ...
    def list_sync_items(self, sync_run_id: str) -> list[InstagramSyncItem]: ...

    def upsert_insight_import(self, insight_import: InstagramInsightImport) -> InstagramInsightImport: ...
    def get_insight_import(self, insight_import_id: str) -> InstagramInsightImport | None: ...
    def list_insight_imports(self, creator_id: str, *, account_id: str | None = None) -> list[InstagramInsightImport]: ...

    def upsert_insight_value(self, insight_value: InstagramInsightValue) -> InstagramInsightValue: ...
    def list_insight_values(self, insight_import_id: str) -> list[InstagramInsightValue]: ...

    def upsert_content_link(self, link: InstagramContentLink) -> InstagramContentLink: ...
    def get_content_link(self, link_id: str) -> InstagramContentLink | None: ...
    def list_content_links(self, creator_id: str) -> list[InstagramContentLink]: ...

    def upsert_rate_limit_usage(self, usage: InstagramRateLimitUsage) -> InstagramRateLimitUsage: ...
    def list_rate_limit_usage(self, connection_id: str) -> list[InstagramRateLimitUsage]: ...

    def upsert_sync_schedule(self, schedule: InstagramSyncSchedule) -> InstagramSyncSchedule: ...
    def list_sync_schedules(self, creator_id: str, *, connection_id: str | None = None) -> list[InstagramSyncSchedule]: ...

    def get_latest_sync_run(self, creator_id: str, *, connection_id: str | None = None) -> InstagramSyncRun | None: ...

