"""Dominio de componentes locales y catalogo versionado."""

from .catalog import (
    DEFAULT_COMPONENT_CATALOG_VERSION,
    DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
    build_default_component_catalog,
    build_default_transcription_profiles,
)
from .downloads import (
    ALLOWED_DOWNLOAD_STATUS_TRANSITIONS,
    ComponentDownloadArtifact,
    ComponentDownloadError,
    ComponentDownloadErrorCategory,
    ComponentDownloadOverwritePolicy,
    ComponentDownloadPriority,
    ComponentDownloadProgress,
    ComponentDownloadRecord,
    ComponentDownloadRequest,
    ComponentDownloadRetryPolicy,
    ComponentDownloadStatus,
    VerifiedComponentArtifact,
    sanitize_download_url,
    validate_download_transition,
)
from .entities import (
    ComponentCatalog,
    ComponentCatalogEntry,
    ComponentCatalogStatus,
    ComponentCategory,
    ComponentEvent,
    ComponentEventType,
    ComponentInstallation,
    ComponentInstallationStatus,
    ComponentInstallKind,
    RuntimeCheckRecord,
    RuntimeCheckStatus,
)
from .repositories import ComponentManagerRepository

__all__ = [
    "ComponentCatalog",
    "ComponentCatalogEntry",
    "ComponentCatalogStatus",
    "ComponentCategory",
    "ComponentEvent",
    "ComponentEventType",
    "ComponentInstallation",
    "ComponentInstallationStatus",
    "ComponentInstallKind",
    "ComponentDownloadArtifact",
    "ComponentDownloadError",
    "ComponentDownloadErrorCategory",
    "ComponentDownloadOverwritePolicy",
    "ComponentDownloadPriority",
    "ComponentDownloadProgress",
    "ComponentDownloadRecord",
    "ComponentDownloadRequest",
    "ComponentDownloadRetryPolicy",
    "ComponentDownloadStatus",
    "VerifiedComponentArtifact",
    "ComponentManagerRepository",
    "RuntimeCheckRecord",
    "RuntimeCheckStatus",
    "ALLOWED_DOWNLOAD_STATUS_TRANSITIONS",
    "DEFAULT_COMPONENT_CATALOG_VERSION",
    "DEFAULT_TRANSCRIPTION_PROFILE_VERSION",
    "build_default_component_catalog",
    "build_default_transcription_profiles",
    "sanitize_download_url",
    "validate_download_transition",
]
