"""Catalogo y perfiles base para Component Manager v32."""

from __future__ import annotations

from datetime import datetime, timezone

from .entities import (
    ComponentCatalog,
    ComponentCatalogEntry,
    ComponentCatalogStatus,
    ComponentCategory,
)
from creator_intelligence_studio.domain.transcription.profiles import (
    DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
    TranscriptionProfileDefinition,
    TranscriptionProfileStatus,
)

DEFAULT_COMPONENT_CATALOG_VERSION = 1
FFMPEG_PRODUCT_RELEASE_TAG = "autobuild-2026-08-09-13-03"
FFMPEG_PRODUCT_ASSET_NAME = "ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip"
FFMPEG_PRODUCT_SOURCE_URL = (
    "https://github.com/BtbN/FFmpeg-Builds/releases/download/"
    "autobuild-2026-08-09-13-03/ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip"
)
FFMPEG_PRODUCT_EXPECTED_SHA256 = "6b4edff47f121d2ed218b1b19d17f67aed08f9f1c9cbcee576fd0548a748c412"
FFMPEG_PRODUCT_EXPECTED_DOWNLOAD_BYTES = 145937826
FFMPEG_PRODUCT_SOURCE_REFERENCE = "https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2026-08-09-13-03"


def _reviewed_now() -> datetime:
    return datetime.now(tz=timezone.utc)


def build_default_component_catalog(*, reviewed_at: datetime | None = None) -> ComponentCatalog:
    """Construye el catalogo base sin realizar red ni instalacion."""

    reviewed_at = reviewed_at or _reviewed_now()
    entries = (
        ComponentCatalogEntry(
            component_id="ffmpeg",
            display_name="FFmpeg",
            category=ComponentCategory.FFMPEG,
            version="8.1.2",
            revision="34-g9b6c8969e0",
            platform="windows",
            architecture="x86_64",
            source_type="approved_product_source",
            source_identifier="btbn/autobuild-2026-08-09-13-03/ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip",
            source_provider="btbn",
            upstream_project="ffmpeg",
            source_url=FFMPEG_PRODUCT_SOURCE_URL,
            release_tag=FFMPEG_PRODUCT_RELEASE_TAG,
            asset_name=FFMPEG_PRODUCT_ASSET_NAME,
            expected_sha256=FFMPEG_PRODUCT_EXPECTED_SHA256,
            upstream_version="8.1.2",
            build_revision="34-g9b6c8969e0",
            license_variant="lgpl",
            source_page_reference=FFMPEG_PRODUCT_SOURCE_REFERENCE,
            verified_at=reviewed_at,
            allowed_domains=("github.com", "release-assets.githubusercontent.com"),
            expected_download_bytes=FFMPEG_PRODUCT_EXPECTED_DOWNLOAD_BYTES,
            dependencies=(),
            capabilities_enabled=("audio_preparation", "media_inspection"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="managed_product_bundle",
            health_check="ffmpeg_version_probe",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="ffprobe",
            display_name="FFprobe",
            category=ComponentCategory.FFMPEG,
            version=None,
            revision=None,
            platform="windows",
            architecture="x64",
            source_type="managed_local_bundle",
            source_identifier=None,
            allowed_domains=(),
            dependencies=("ffmpeg",),
            capabilities_enabled=("media_inspection",),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="managed_local_bundle",
            health_check="ffprobe_version_probe",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-runtime.faster-whisper",
            display_name="faster-whisper runtime",
            category=ComponentCategory.TRANSCRIPTION_RUNTIME,
            version="1.2.1",
            revision="0",
            platform="python",
            architecture="any",
            source_type="python_package",
            source_identifier="pyproject.toml",
            allowed_domains=(),
            dependencies=("faster-whisper", "ctranslate2"),
            capabilities_enabled=("local_transcription", "word_timestamps", "vad_filter"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="python_package",
            health_check="python_import",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-runtime.ctranslate2",
            display_name="CTranslate2 runtime",
            category=ComponentCategory.TRANSCRIPTION_RUNTIME,
            version="4.8.1",
            revision="0",
            platform="python",
            architecture="any",
            source_type="python_package",
            source_identifier="pyproject.toml",
            allowed_domains=(),
            dependencies=(),
            capabilities_enabled=("local_transcription", "cuda_acceleration"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="python_package",
            health_check="python_import",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.base",
            display_name="Transcription model base",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="base",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-base",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.small",
            display_name="Transcription model small",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="small",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-small",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.medium",
            display_name="Transcription model medium",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="medium",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-medium",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.large-v3-turbo",
            display_name="Transcription model large-v3-turbo",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="large-v3-turbo",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-large-v3-turbo",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.large-v3",
            display_name="Transcription model large-v3",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="large-v3",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-large-v3",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
    )
    return ComponentCatalog(
        catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
        entries=entries,
        reviewed_at=reviewed_at,
    )


def build_default_transcription_profiles(*, reviewed_at: datetime | None = None) -> tuple[TranscriptionProfileDefinition, ...]:
    """Construye perfiles versionados para el resolver de transcripcion."""

    reviewed_at = reviewed_at or _reviewed_now()
    return (
        TranscriptionProfileDefinition(
            profile_id="fast",
            display_name="Rapido",
            description="Prioriza rapidez con un modelo pequeno y configuracion conservadora.",
            model_component_id="transcription-model.base",
            model_revision="1",
            device_policy="cpu_preferred",
            cpu_compute_type="int8",
            gpu_compute_type="int8_float16",
            beam_size=1,
            vad_policy="disabled",
            language_detection="auto",
            word_timestamps=False,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="balanced",
            display_name="Equilibrado",
            description="Perfil predeterminado con equilibrio entre costo, velocidad y calidad.",
            model_component_id="transcription-model.small",
            model_revision="1",
            device_policy="automatic",
            cpu_compute_type="int8",
            gpu_compute_type="int8_float16",
            beam_size=5,
            vad_policy="disabled",
            language_detection="auto",
            word_timestamps=False,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="maximum_quality",
            display_name="Maxima calidad",
            description="Perfil conservador para priorizar calidad sobre velocidad.",
            model_component_id="transcription-model.medium",
            model_revision="1",
            device_policy="gpu_preferred",
            cpu_compute_type="int8",
            gpu_compute_type="float16",
            beam_size=5,
            vad_policy="enabled",
            language_detection="auto",
            word_timestamps=True,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="custom",
            display_name="Personalizado",
            description="Representacion avanzada para ajustes tecnicos manuales.",
            model_component_id=None,
            model_revision=None,
            device_policy="manual",
            cpu_compute_type=None,
            gpu_compute_type=None,
            beam_size=None,
            vad_policy="manual",
            language_detection="manual",
            word_timestamps=None,
            segment_timestamps=None,
            batching_policy="manual",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.UNKNOWN,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
    )
