"""Catalogo y perfiles base para Component Manager v32."""

from __future__ import annotations

from datetime import datetime, timezone

from .entities import (
    ComponentCatalog,
    ComponentCatalogEntry,
    ComponentCatalogStatus,
    ComponentCategory,
)
from creator_intelligence_studio.domain.transcription.profiles import (
    DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
    TranscriptionProfileDefinition,
    TranscriptionProfileStatus,
)
from creator_intelligence_studio.domain.transcription.model_sources import (
    get_transcription_model_source_manifest,
)
from creator_intelligence_studio.domain.semantic_embedding.model_sources import (
    get_semantic_embedding_model_manifest,
)

DEFAULT_COMPONENT_CATALOG_VERSION = 1
FFMPEG_PRODUCT_RELEASE_TAG = "autobuild-2026-07-31-14-10"
FFMPEG_PRODUCT_ASSET_NAME = "ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip"
FFMPEG_PRODUCT_SOURCE_URL = (
    "https://github.com/BtbN/FFmpeg-Builds/releases/download/"
    "autobuild-2026-07-31-14-10/ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip"
)
FFMPEG_PRODUCT_EXPECTED_SHA256 = "089e4169e93b2b3f3acbfced3c0704d24276a225641bdda04d796d28b07a2a38"
FFMPEG_PRODUCT_EXPECTED_DOWNLOAD_BYTES = 145349121
FFMPEG_PRODUCT_SOURCE_REFERENCE = "https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2026-07-31-14-10"
SMALL_MODEL_SOURCE_MANIFEST = get_transcription_model_source_manifest("transcription-model.small")
SEMANTIC_MODEL_SOURCE_MANIFEST = get_semantic_embedding_model_manifest("creator-embedding-model.multilingual-e5-small")


def _reviewed_now() -> datetime:
    return datetime.now(tz=timezone.utc)


def build_default_component_catalog(*, reviewed_at: datetime | None = None) -> ComponentCatalog:
    """Construye el catalogo base sin realizar red ni instalacion."""

    reviewed_at = reviewed_at or _reviewed_now()
    entries = (
        ComponentCatalogEntry(
            component_id="ffmpeg",
            display_name="FFmpeg",
            category=ComponentCategory.FFMPEG,
            version="8.1.2",
            revision="34-g9b6c8969e0",
            platform="windows",
            architecture="x86_64",
            source_type="approved_product_source",
            source_identifier="btbn/autobuild-2026-07-31-14-10/ffmpeg-n8.1.2-34-g9b6c8969e0-win64-lgpl-8.1.zip",
            source_provider="btbn",
            upstream_project="ffmpeg",
            source_url=FFMPEG_PRODUCT_SOURCE_URL,
            release_tag=FFMPEG_PRODUCT_RELEASE_TAG,
            asset_name=FFMPEG_PRODUCT_ASSET_NAME,
            expected_sha256=FFMPEG_PRODUCT_EXPECTED_SHA256,
            upstream_version="8.1.2",
            build_revision="34-g9b6c8969e0",
            license_variant="lgpl",
            source_page_reference=FFMPEG_PRODUCT_SOURCE_REFERENCE,
            verified_at=reviewed_at,
            allowed_domains=("github.com", "release-assets.githubusercontent.com"),
            expected_download_bytes=FFMPEG_PRODUCT_EXPECTED_DOWNLOAD_BYTES,
            dependencies=(),
            capabilities_enabled=("audio_preparation", "media_inspection"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="managed_product_bundle",
            health_check="ffmpeg_version_probe",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="ffprobe",
            display_name="FFprobe",
            category=ComponentCategory.FFMPEG,
            version=None,
            revision=None,
            platform="windows",
            architecture="x64",
            source_type="managed_local_bundle",
            source_identifier=None,
            allowed_domains=(),
            dependencies=("ffmpeg",),
            capabilities_enabled=("media_inspection",),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="managed_local_bundle",
            health_check="ffprobe_version_probe",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-runtime.faster-whisper",
            display_name="faster-whisper runtime",
            category=ComponentCategory.TRANSCRIPTION_RUNTIME,
            version="1.2.1",
            revision="0",
            platform="python",
            architecture="any",
            source_type="python_package",
            source_identifier="pyproject.toml",
            allowed_domains=(),
            dependencies=("faster-whisper", "ctranslate2"),
            capabilities_enabled=("local_transcription", "word_timestamps", "vad_filter"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="python_package",
            health_check="python_import",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-runtime.ctranslate2",
            display_name="CTranslate2 runtime",
            category=ComponentCategory.TRANSCRIPTION_RUNTIME,
            version="4.8.1",
            revision="0",
            platform="python",
            architecture="any",
            source_type="python_package",
            source_identifier="pyproject.toml",
            allowed_domains=(),
            dependencies=(),
            capabilities_enabled=("local_transcription", "cuda_acceleration"),
            minimum_requirements={},
            recommended_requirements={},
            install_strategy="python_package",
            health_check="python_import",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.base",
            display_name="Transcription model base",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="base",
            revision="1",
            platform="windows",
            architecture="x86_64",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-base",
            allowed_domains=("huggingface.co", "hf.co"),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.small",
            display_name="Transcription model small",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="small",
            revision="1",
            platform="windows",
            architecture="x86_64",
            source_type="approved_product_source",
            source_identifier=f"{SMALL_MODEL_SOURCE_MANIFEST.source_provider}/{SMALL_MODEL_SOURCE_MANIFEST.repository}@{SMALL_MODEL_SOURCE_MANIFEST.revision}" if SMALL_MODEL_SOURCE_MANIFEST else "huggingface/Systran/faster-whisper-small",
            source_provider=SMALL_MODEL_SOURCE_MANIFEST.source_provider if SMALL_MODEL_SOURCE_MANIFEST else "huggingface",
            upstream_project=SMALL_MODEL_SOURCE_MANIFEST.repository if SMALL_MODEL_SOURCE_MANIFEST else "Systran/faster-whisper-small",
            source_url=SMALL_MODEL_SOURCE_MANIFEST.source_page if SMALL_MODEL_SOURCE_MANIFEST else "https://huggingface.co/Systran/faster-whisper-small/tree/main",
            expected_sha256=SMALL_MODEL_SOURCE_MANIFEST.expected_sha256 if SMALL_MODEL_SOURCE_MANIFEST else None,
            upstream_version="small",
            build_revision=SMALL_MODEL_SOURCE_MANIFEST.revision if SMALL_MODEL_SOURCE_MANIFEST else None,
            license_variant=SMALL_MODEL_SOURCE_MANIFEST.license if SMALL_MODEL_SOURCE_MANIFEST else "mit",
            source_page_reference=SMALL_MODEL_SOURCE_MANIFEST.source_page if SMALL_MODEL_SOURCE_MANIFEST else "https://huggingface.co/Systran/faster-whisper-small/tree/main",
            verified_at=reviewed_at,
            allowed_domains=("huggingface.co", "hf.co"),
            expected_download_bytes=SMALL_MODEL_SOURCE_MANIFEST.total_expected_bytes if SMALL_MODEL_SOURCE_MANIFEST else None,
            expected_installed_bytes=SMALL_MODEL_SOURCE_MANIFEST.total_expected_bytes if SMALL_MODEL_SOURCE_MANIFEST else None,
            temporary_space_bytes=SMALL_MODEL_SOURCE_MANIFEST.total_expected_bytes if SMALL_MODEL_SOURCE_MANIFEST else None,
            license_name="MIT",
            license_url=SMALL_MODEL_SOURCE_MANIFEST.source_page if SMALL_MODEL_SOURCE_MANIFEST else "https://huggingface.co/Systran/faster-whisper-small/tree/main",
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.medium",
            display_name="Transcription model medium",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="medium",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-medium",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.VERIFIED,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.large-v3-turbo",
            display_name="Transcription model large-v3-turbo",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="large-v3-turbo",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-large-v3-turbo",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="transcription-model.large-v3",
            display_name="Transcription model large-v3",
            category=ComponentCategory.TRANSCRIPTION_MODEL,
            version="large-v3",
            revision="1",
            platform="huggingface",
            architecture="any",
            source_type="huggingface_snapshot",
            source_identifier="Systran/faster-whisper-large-v3",
            allowed_domains=("huggingface.co",),
            capabilities_enabled=("local_transcription",),
            install_strategy="model_directory_activate",
            health_check="local_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
        ComponentCatalogEntry(
            component_id="creator-embedding-model.multilingual-e5-small",
            display_name="Búsqueda inteligente",
            category=ComponentCategory.SEMANTIC_MODEL,
            version="multilingual-e5-small",
            revision=SEMANTIC_MODEL_SOURCE_MANIFEST.revision if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            platform="windows",
            architecture="x86_64",
            source_type="approved_product_source",
            source_identifier=f"{SEMANTIC_MODEL_SOURCE_MANIFEST.source_provider}/{SEMANTIC_MODEL_SOURCE_MANIFEST.repository}@{SEMANTIC_MODEL_SOURCE_MANIFEST.revision}" if SEMANTIC_MODEL_SOURCE_MANIFEST else "huggingface/intfloat/multilingual-e5-small",
            source_provider=SEMANTIC_MODEL_SOURCE_MANIFEST.source_provider if SEMANTIC_MODEL_SOURCE_MANIFEST else "huggingface",
            upstream_project=SEMANTIC_MODEL_SOURCE_MANIFEST.repository if SEMANTIC_MODEL_SOURCE_MANIFEST else "intfloat/multilingual-e5-small",
            source_url=SEMANTIC_MODEL_SOURCE_MANIFEST.source_page if SEMANTIC_MODEL_SOURCE_MANIFEST else "https://huggingface.co/intfloat/multilingual-e5-small/tree/614241f622f53c4eeff9890bdc4f31cfecc418b3",
            expected_sha256=SEMANTIC_MODEL_SOURCE_MANIFEST.expected_sha256 if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            upstream_version="multilingual-e5-small",
            build_revision=SEMANTIC_MODEL_SOURCE_MANIFEST.revision if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            license_variant=SEMANTIC_MODEL_SOURCE_MANIFEST.license if SEMANTIC_MODEL_SOURCE_MANIFEST else "mit",
            source_page_reference=SEMANTIC_MODEL_SOURCE_MANIFEST.source_page if SEMANTIC_MODEL_SOURCE_MANIFEST else "https://huggingface.co/intfloat/multilingual-e5-small/tree/614241f622f53c4eeff9890bdc4f31cfecc418b3",
            verified_at=reviewed_at,
            allowed_domains=("huggingface.co", "hf.co"),
            expected_download_bytes=SEMANTIC_MODEL_SOURCE_MANIFEST.selected_cpu_artifact.expected_bytes if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            expected_installed_bytes=SEMANTIC_MODEL_SOURCE_MANIFEST.total_expected_bytes if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            temporary_space_bytes=SEMANTIC_MODEL_SOURCE_MANIFEST.total_expected_bytes if SEMANTIC_MODEL_SOURCE_MANIFEST else None,
            license_name="MIT",
            license_url=SEMANTIC_MODEL_SOURCE_MANIFEST.source_page if SEMANTIC_MODEL_SOURCE_MANIFEST else "https://huggingface.co/intfloat/multilingual-e5-small/tree/614241f622f53c4eeff9890bdc4f31cfecc418b3",
            capabilities_enabled=("semantic_retrieval", "hybrid_retrieval"),
            install_strategy="model_directory_activate",
            health_check="local_embedding_model_presence",
            rollback_supported=False,
            catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
            reviewed_at=reviewed_at,
            status=ComponentCatalogStatus.PENDING_VERIFICATION,
            created_at=reviewed_at,
            updated_at=reviewed_at,
        ),
    )
    return ComponentCatalog(
        catalog_version=DEFAULT_COMPONENT_CATALOG_VERSION,
        entries=entries,
        reviewed_at=reviewed_at,
    )


def build_default_transcription_profiles(*, reviewed_at: datetime | None = None) -> tuple[TranscriptionProfileDefinition, ...]:
    """Construye perfiles versionados para el resolver de transcripcion."""

    reviewed_at = reviewed_at or _reviewed_now()
    return (
        TranscriptionProfileDefinition(
            profile_id="fast",
            display_name="Rapido",
            description="Prioriza rapidez con un modelo pequeno y configuracion conservadora.",
            model_component_id="transcription-model.base",
            model_revision="1",
            device_policy="cpu_preferred",
            cpu_compute_type="int8",
            gpu_compute_type="int8_float16",
            beam_size=1,
            vad_policy="disabled",
            language_detection="auto",
            word_timestamps=False,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="balanced",
            display_name="Equilibrado",
            description="Perfil predeterminado con equilibrio entre costo, velocidad y calidad.",
            model_component_id="transcription-model.small",
            model_revision="1",
            device_policy="automatic",
            cpu_compute_type="int8",
            gpu_compute_type="int8_float16",
            beam_size=5,
            vad_policy="disabled",
            language_detection="auto",
            word_timestamps=False,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="maximum_quality",
            display_name="Maxima calidad",
            description="Perfil conservador para priorizar calidad sobre velocidad.",
            model_component_id="transcription-model.medium",
            model_revision="1",
            device_policy="gpu_preferred",
            cpu_compute_type="int8",
            gpu_compute_type="float16",
            beam_size=5,
            vad_policy="enabled",
            language_detection="auto",
            word_timestamps=True,
            segment_timestamps=True,
            batching_policy="single",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.PROVISIONAL,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
        TranscriptionProfileDefinition(
            profile_id="custom",
            display_name="Personalizado",
            description="Representacion avanzada para ajustes tecnicos manuales.",
            model_component_id=None,
            model_revision=None,
            device_policy="manual",
            cpu_compute_type=None,
            gpu_compute_type=None,
            beam_size=None,
            vad_policy="manual",
            language_detection="manual",
            word_timestamps=None,
            segment_timestamps=None,
            batching_policy="manual",
            minimum_ram_gb=None,
            minimum_vram_gb=None,
            recommended_vram_gb=None,
            estimated_disk_bytes=None,
            status=TranscriptionProfileStatus.UNKNOWN,
            version=DEFAULT_TRANSCRIPTION_PROFILE_VERSION,
            reviewed_at=reviewed_at,
        ),
    )
