"""Contrato de persistencia para packaging creativo."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    CreativeConcept,
    CreativePrompt,
    CreativePromptReference,
    PackagingAsset,
    PackagingBrandProfile,
    PackagingDecision,
    PackagingExperimentLink,
    PackagingReferenceAsset,
    PackagingPairEvaluation,
    ThumbnailFrameCandidate,
    ThumbnailReview,
    ThumbnailVersion,
    TitleAnalysisMetric,
    TitleAnalysisRun,
    TitleVersion,
    ThumbnailAnalysisMetric,
    ThumbnailAnalysisRun,
)


class CreativePackagingRepository(Protocol):
    def upsert_asset(self, asset: PackagingAsset) -> PackagingAsset: ...
    def get_asset(self, asset_id: str) -> PackagingAsset | None: ...
    def list_assets(self, creator_id: str) -> list[PackagingAsset]: ...

    def upsert_title_version(self, title: TitleVersion) -> TitleVersion: ...
    def get_title_version(self, title_version_id: str) -> TitleVersion | None: ...
    def list_title_versions(self, packaging_asset_id: str) -> list[TitleVersion]: ...

    def upsert_thumbnail_version(self, thumbnail: ThumbnailVersion) -> ThumbnailVersion: ...
    def get_thumbnail_version(self, thumbnail_version_id: str) -> ThumbnailVersion | None: ...
    def list_thumbnail_versions(self, packaging_asset_id: str) -> list[ThumbnailVersion]: ...

    def upsert_reference_asset(self, reference: PackagingReferenceAsset) -> PackagingReferenceAsset: ...
    def get_reference_asset(self, reference_id: str) -> PackagingReferenceAsset | None: ...
    def list_reference_assets(self, creator_id: str) -> list[PackagingReferenceAsset]: ...

    def upsert_brand_profile(self, profile: PackagingBrandProfile) -> PackagingBrandProfile: ...
    def get_brand_profile(self, creator_id: str) -> PackagingBrandProfile | None: ...
    def list_brand_profiles(self, creator_id: str) -> list[PackagingBrandProfile]: ...

    def upsert_title_analysis_run(self, run: TitleAnalysisRun) -> TitleAnalysisRun: ...
    def get_title_analysis_run(self, run_id: str) -> TitleAnalysisRun | None: ...
    def list_title_analysis_runs(self, creator_id: str) -> list[TitleAnalysisRun]: ...
    def upsert_title_analysis_metric(self, metric: TitleAnalysisMetric) -> TitleAnalysisMetric: ...
    def list_title_analysis_metrics(self, run_id: str) -> list[TitleAnalysisMetric]: ...

    def upsert_thumbnail_analysis_run(self, run: ThumbnailAnalysisRun) -> ThumbnailAnalysisRun: ...
    def get_thumbnail_analysis_run(self, run_id: str) -> ThumbnailAnalysisRun | None: ...
    def list_thumbnail_analysis_runs(self, creator_id: str) -> list[ThumbnailAnalysisRun]: ...
    def upsert_thumbnail_analysis_metric(self, metric: ThumbnailAnalysisMetric) -> ThumbnailAnalysisMetric: ...
    def list_thumbnail_analysis_metrics(self, run_id: str) -> list[ThumbnailAnalysisMetric]: ...

    def upsert_pair_evaluation(self, evaluation: PackagingPairEvaluation) -> PackagingPairEvaluation: ...
    def get_pair_evaluation(self, evaluation_id: str) -> PackagingPairEvaluation | None: ...
    def list_pair_evaluations(self, creator_id: str) -> list[PackagingPairEvaluation]: ...

    def upsert_frame_candidate(self, candidate: ThumbnailFrameCandidate) -> ThumbnailFrameCandidate: ...
    def list_frame_candidates(self, creator_id: str, video_asset_id: str | None = None) -> list[ThumbnailFrameCandidate]: ...

    def upsert_concept(self, concept: CreativeConcept) -> CreativeConcept: ...
    def get_concept(self, concept_id: str) -> CreativeConcept | None: ...
    def list_concepts(self, creator_id: str) -> list[CreativeConcept]: ...

    def upsert_prompt(self, prompt: CreativePrompt) -> CreativePrompt: ...
    def get_prompt(self, prompt_id: str) -> CreativePrompt | None: ...
    def list_prompts(self, concept_id: str) -> list[CreativePrompt]: ...
    def upsert_prompt_reference(self, reference: CreativePromptReference) -> CreativePromptReference: ...
    def list_prompt_references(self, prompt_id: str) -> list[CreativePromptReference]: ...

    def upsert_thumbnail_review(self, review: ThumbnailReview) -> ThumbnailReview: ...
    def get_thumbnail_review(self, review_id: str) -> ThumbnailReview | None: ...
    def list_thumbnail_reviews(self, creator_id: str) -> list[ThumbnailReview]: ...

    def upsert_decision(self, decision: PackagingDecision) -> PackagingDecision: ...
    def list_decisions(self, creator_id: str) -> list[PackagingDecision]: ...

    def upsert_experiment_link(self, link: PackagingExperimentLink) -> PackagingExperimentLink: ...
    def list_experiment_links(self, packaging_asset_id: str) -> list[PackagingExperimentLink]: ...

