"""Enumeraciones del dominio de production preparation."""

from __future__ import annotations

from enum import Enum


class _StrEnum(str, Enum):
    def __str__(self) -> str:  # pragma: no cover - conveniencia
        return self.value


class ProductionRequestStatus(_StrEnum):
    DRAFT = "draft"
    QUEUED = "queued"
    ASSEMBLING_CONTEXT = "assembling_context"
    VALIDATING_BRIEF = "validating_brief"
    BUILDING_OUTLINE = "building_outline"
    BUILDING_SECTIONS = "building_sections"
    BUILDING_BEATS = "building_beats"
    BUILDING_SEGMENTS = "building_segments"
    MAPPING_CLAIMS = "mapping_claims"
    MAPPING_PROOFS = "mapping_proofs"
    BUILDING_SCENES = "building_scenes"
    BUILDING_SHOTS = "building_shots"
    BUILDING_RECORDING_BLOCKS = "building_recording_blocks"
    BUILDING_VARIANTS = "building_variants"
    BUILDING_CHECKLISTS = "building_checklists"
    CALCULATING_READINESS = "calculating_readiness"
    SAVING = "saving"
    COMPLETED = "completed"
    COMPLETED_WITH_WARNINGS = "completed_with_warnings"
    INTERRUPTED = "interrupted"
    CANCELLED = "cancelled"
    FAILED = "failed"


class ScriptOutlineType(_StrEnum):
    SHORT_VIDEO_OUTLINE = "short_video_outline"
    LONGFORM_VIDEO_OUTLINE = "longform_video_outline"
    LIVESTREAM_OUTLINE = "livestream_outline"
    PODCAST_OUTLINE = "podcast_outline"
    AUDIO_OUTLINE = "audio_outline"
    CAROUSEL_OUTLINE = "carousel_outline"
    STORY_OUTLINE = "story_outline"
    IMAGE_POST_OUTLINE = "image_post_outline"
    ARTICLE_OUTLINE = "article_outline"
    NEWSLETTER_OUTLINE = "newsletter_outline"
    COMMUNITY_POST_OUTLINE = "community_post_outline"
    REPURPOSE_OUTLINE = "repurpose_outline"
    EXPERIMENT_OUTLINE = "experiment_outline"
    TUTORIAL_OUTLINE = "tutorial_outline"
    INTERVIEW_OUTLINE = "interview_outline"
    DEMONSTRATION_OUTLINE = "demonstration_outline"
    CASE_STUDY_OUTLINE = "case_study_outline"
    UNKNOWN = "unknown"


class ScriptOutlineStatus(_StrEnum):
    DRAFT = "draft"
    ASSEMBLING = "assembling"
    NEEDS_INFORMATION = "needs_information"
    NEEDS_REVIEW = "needs_review"
    APPROVED = "approved"
    READY_FOR_SCENE_PLANNING = "ready_for_scene_planning"
    SCENE_PLANNING = "scene_planning"
    READY_FOR_RECORDING_PREPARATION = "ready_for_recording_preparation"
    RECORDING_PREPARATION = "recording_preparation"
    BLOCKED = "blocked"
    READY_FOR_RECORDING = "ready_for_recording"
    RECORDING_IN_PROGRESS = "recording_in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    SUPERSEDED = "superseded"
    ARCHIVED = "archived"


class OutlineSectionType(_StrEnum):
    OPENING = "opening"
    HOOK = "hook"
    SETUP = "setup"
    CONTEXT = "context"
    PROBLEM = "problem"
    PROMISE = "promise"
    EXPLANATION = "explanation"
    DEMONSTRATION = "demonstration"
    EVIDENCE = "evidence"
    EXAMPLE = "example"
    COMPARISON = "comparison"
    ESCALATION = "escalation"
    TURNING_POINT = "turning_point"
    SOLUTION = "solution"
    APPLICATION = "application"
    RECAP = "recap"
    CALL_TO_ACTION_DIRECTION = "call_to_action_direction"
    CLOSING = "closing"
    CREDITS_DIRECTION = "credits_direction"
    DISCLAIMER_DIRECTION = "disclaimer_direction"
    PLATFORM_SPECIFIC = "platform_specific"
    CUSTOM = "custom"


class BeatType(_StrEnum):
    ATTENTION = "attention"
    IDENTIFICATION = "identification"
    CURIOSITY = "curiosity"
    CONFLICT = "conflict"
    QUESTION = "question"
    PROMISE = "promise"
    CONTEXT = "context"
    REVEAL = "reveal"
    EXPLANATION = "explanation"
    PROOF = "proof"
    EXAMPLE = "example"
    DEMONSTRATION = "demonstration"
    OBJECTION = "objection"
    CORRECTION = "correction"
    ESCALATION = "escalation"
    TRANSITION = "transition"
    PAYOFF = "payoff"
    SUMMARY = "summary"
    ACTION_DIRECTION = "action_direction"
    EMOTIONAL_SHIFT = "emotional_shift"
    PATTERN_INTERRUPT = "pattern_interrupt"
    RETENTION_RESET = "retention_reset"
    CUSTOM = "custom"


class SegmentType(_StrEnum):
    SPOKEN_DIRECTION = "spoken_direction"
    DEMONSTRATION = "demonstration"
    VISUAL_EXPLANATION = "visual_explanation"
    SCREEN_RECORDING = "screen_recording"
    B_ROLL = "b_roll"
    GRAPHIC = "graphic"
    DATA_VISUALIZATION = "data_visualization"
    INTERVIEW_QUESTION_DIRECTION = "interview_question_direction"
    REACTION = "reaction"
    EXAMPLE = "example"
    EXERCISE = "exercise"
    TRANSITION = "transition"
    RECAP = "recap"
    CTA_DIRECTION = "cta_direction"
    DISCLAIMER_DIRECTION = "disclaimer_direction"
    SILENCE_OR_PAUSE_DIRECTION = "silence_or_pause_direction"
    PLATFORM_VARIANT = "platform_variant"
    CUSTOM = "custom"


class ShotType(_StrEnum):
    TALKING_HEAD = "talking_head"
    CLOSE_UP = "close_up"
    MEDIUM = "medium"
    WIDE = "wide"
    EXTREME_CLOSE_UP = "extreme_close_up"
    OVER_SHOULDER = "over_shoulder"
    TOP_DOWN = "top_down"
    POINT_OF_VIEW = "point_of_view"
    SCREEN_CAPTURE = "screen_capture"
    DEMONSTRATION = "demonstration"
    PRODUCT = "product"
    B_ROLL = "b_roll"
    REACTION = "reaction"
    INSERT = "insert"
    CUTAWAY = "cutaway"
    TRANSITION = "transition"
    ESTABLISHING = "establishing"
    GRAPHIC_PLACEHOLDER = "graphic_placeholder"
    TEXT_PLACEHOLDER = "text_placeholder"
    DATA_VISUALIZATION_PLACEHOLDER = "data_visualization_placeholder"
    TITLE_CARD_PLACEHOLDER = "title_card_placeholder"
    CUSTOM = "custom"


class RecordingBlockType(_StrEnum):
    PRIMARY_TALKING_HEAD = "primary_talking_head"
    DEMONSTRATION = "demonstration"
    B_ROLL = "b_roll"
    SCREEN_RECORDING = "screen_recording"
    VOICEOVER_DIRECTION = "voiceover_direction"
    PARTICIPANT_SESSION = "participant_session"
    PRODUCT_SESSION = "product_session"
    LOCATION_SESSION = "location_session"
    PICKUP_SESSION = "pickup_session"
    PLATFORM_VARIANT_SESSION = "platform_variant_session"
    CUSTOM = "custom"


class CueType(_StrEnum):
    SUBJECT_ACTION = "subject_action"
    OBJECT_DEMONSTRATION = "object_demonstration"
    CAMERA_DIRECTION = "camera_direction"
    FRAMING_DIRECTION = "framing_direction"
    MOVEMENT_DIRECTION = "movement_direction"
    COMPOSITION_DIRECTION = "composition_direction"
    LIGHTING_DIRECTION = "lighting_direction"
    BACKGROUND_DIRECTION = "background_direction"
    GRAPHIC_DIRECTION = "graphic_direction"
    B_ROLL_DIRECTION = "b_roll_direction"
    SCREEN_DIRECTION = "screen_direction"
    TRANSITION_DIRECTION = "transition_direction"
    TEXT_DIRECTION = "text_direction"
    VISUAL_PROOF = "visual_proof"
    SPOKEN_DIRECTION = "spoken_direction"
    AMBIENT_DIRECTION = "ambient_direction"
    MUSIC_DIRECTION = "music_direction"
    SOUND_EFFECT_DIRECTION = "sound_effect_direction"
    SILENCE_DIRECTION = "silence_direction"
    TRANSITION_SOUND_DIRECTION = "transition_sound_direction"
    VOICEOVER_DIRECTION = "voiceover_direction"
    EMPHASIS_DIRECTION = "emphasis_direction"
    CLEANUP_REQUIREMENT = "cleanup_requirement"
    RIGHTS_WARNING = "rights_warning"


class TextDirectionType(_StrEnum):
    TEXT_DIRECTION = "text_direction"
    LABEL = "label"
    KEYWORD = "keyword"
    STATISTIC_PLACEHOLDER = "statistic_placeholder"
    DISCLAIMER_PLACEHOLDER = "disclaimer_placeholder"
    CTA_DIRECTION = "cta_direction"
    SUBTITLE_DIRECTION = "subtitle_direction"
    CHAPTER_DIRECTION = "chapter_direction"
    GRAPHIC_LABEL = "graphic_label"
    CUSTOM = "custom"


class ContinuityType(_StrEnum):
    WARDROBE = "wardrobe"
    PROP = "prop"
    LOCATION = "location"
    LIGHTING = "lighting"
    TIME_OF_DAY = "time_of_day"
    SCREEN_STATE = "screen_state"
    DEVICE_STATE = "device_state"
    PARTICIPANT_POSITION = "participant_position"
    OBJECT_POSITION = "object_position"
    AUDIO_ENVIRONMENT = "audio_environment"
    CAMERA_SETTINGS = "camera_settings"
    HAIR_MAKEUP = "hair_makeup"
    NARRATIVE = "narrative"
    DATA_STATE = "data_state"
    CUSTOM = "custom"


class ParticipantType(_StrEnum):
    CREATOR = "creator"
    GUEST = "guest"
    EXPERT = "expert"
    INTERVIEWER = "interviewer"
    SUBJECT = "subject"
    ACTOR = "actor"
    MINOR = "minor"
    CREW = "crew"
    VOICE_ONLY = "voice_only"
    HANDS_ONLY = "hands_only"
    ANONYMOUS_PARTICIPANT = "anonymous_participant"
    CUSTOM = "custom"


class LocationType(_StrEnum):
    STUDIO = "studio"
    HOME = "home"
    OFFICE = "office"
    EXTERIOR = "exterior"
    BACKDROP = "backdrop"
    SCREEN_ONLY = "screen_only"
    CUSTOM = "custom"


class EquipmentType(_StrEnum):
    CAMERA = "camera"
    LENS = "lens"
    PHONE = "phone"
    TRIPOD = "tripod"
    GIMBAL = "gimbal"
    MICROPHONE = "microphone"
    RECORDER = "recorder"
    LIGHTING = "lighting"
    MONITOR = "monitor"
    COMPUTER = "computer"
    CAPTURE_DEVICE = "capture_device"
    SCREEN_RECORDER = "screen_recorder"
    TELEPROMPTER = "teleprompter"
    STORAGE = "storage"
    POWER = "power"
    NETWORK = "network"
    BACKDROP = "backdrop"
    PROP_EQUIPMENT = "prop_equipment"
    SAFETY_EQUIPMENT = "safety_equipment"
    CUSTOM = "custom"


class AssetType(_StrEnum):
    SCRIPT_REFERENCE = "script_reference"
    OUTLINE_ASSET = "outline_asset"
    SCENE_REFERENCE = "scene_reference"
    SHOT_REFERENCE = "shot_reference"
    GRAPHIC = "graphic"
    B_ROLL = "b_roll"
    SCREEN_RECORDING = "screen_recording"
    PARTICIPANT_RELEASE = "participant_release"
    LOCATION_PERMISSION = "location_permission"
    EQUIPMENT = "equipment"
    WARDROBE = "wardrobe"
    PROP = "prop"
    CUSTOM = "custom"


class DependencyType(_StrEnum):
    BRIEF_APPROVAL = "brief_approval"
    CLAIM_VERIFICATION = "claim_verification"
    RIGHTS_APPROVAL = "rights_approval"
    PARTICIPANT_RELEASE = "participant_release"
    LOCATION_PERMISSION = "location_permission"
    ASSET_READINESS = "asset_readiness"
    EQUIPMENT_AVAILABILITY = "equipment_availability"
    PLATFORM_ACCESS = "platform_access"
    SCREEN_RECORDING_PERMISSION = "screen_recording_permission"
    EXPERIMENT_SETUP = "experiment_setup"
    MEASUREMENT_SETUP = "measurement_setup"
    CONTENT_LIBRARY_ASSET = "content_library_asset"
    PACKAGING_DIRECTION = "packaging_direction"
    PRODUCTION_APPROVAL = "production_approval"
    CUSTOM = "custom"


class MilestoneType(_StrEnum):
    OUTLINE_APPROVED = "outline_approved"
    CLAIMS_CLEARED = "claims_cleared"
    RIGHTS_CLEARED = "rights_cleared"
    SCENES_APPROVED = "scenes_approved"
    SHOT_LIST_APPROVED = "shot_list_approved"
    PARTICIPANTS_CONFIRMED = "participants_confirmed"
    LOCATIONS_CONFIRMED = "locations_confirmed"
    ASSETS_READY = "assets_ready"
    EQUIPMENT_READY = "equipment_ready"
    RECORDING_BLOCKS_APPROVED = "recording_blocks_approved"
    CONTINUITY_REVIEWED = "continuity_reviewed"
    PLATFORM_VARIANTS_APPROVED = "platform_variants_approved"
    RECORDING_READINESS_APPROVED = "recording_readiness_approved"
    CUSTOM = "custom"


class ReadinessStatus(_StrEnum):
    NOT_STARTED = "not_started"
    INCOMPLETE = "incomplete"
    NEEDS_INFORMATION = "needs_information"
    NEEDS_REVIEW = "needs_review"
    BLOCKED = "blocked"
    CONDITIONALLY_READY = "conditionally_ready"
    READY_FOR_SCENE_PLANNING = "ready_for_scene_planning"
    SCENE_PLANNING = "scene_planning"
    READY_FOR_RECORDING_PREPARATION = "ready_for_recording_preparation"
    RECORDING_PREPARATION = "recording_preparation"
    READY_FOR_RECORDING = "ready_for_recording"
    UNKNOWN = "unknown"


class ApprovalGateType(_StrEnum):
    OUTLINE_APPROVAL = "outline_approval"
    NARRATIVE_APPROVAL = "narrative_approval"
    CLAIM_APPROVAL = "claim_approval"
    CREATOR_LANGUAGE_APPROVAL = "creator_language_approval"
    SCENE_APPROVAL = "scene_approval"
    SHOT_LIST_APPROVAL = "shot_list_approval"
    VISUAL_DIRECTION_APPROVAL = "visual_direction_approval"
    AUDIO_DIRECTION_APPROVAL = "audio_direction_approval"
    RIGHTS_APPROVAL = "rights_approval"
    PARTICIPANT_APPROVAL = "participant_approval"
    LOCATION_APPROVAL = "location_approval"
    EQUIPMENT_APPROVAL = "equipment_approval"
    CONTINUITY_APPROVAL = "continuity_approval"
    PLATFORM_VARIANT_APPROVAL = "platform_variant_approval"
    MEASUREMENT_APPROVAL = "measurement_approval"
    FINAL_RECORDING_READINESS = "final_recording_readiness"
    CUSTOM = "custom"


class RiskType(_StrEnum):
    CLAIM = "claim"
    MISINFORMATION = "misinformation"
    COPYING = "copying"
    RIGHTS = "rights"
    PARTICIPANT = "participant"
    MINOR_PARTICIPANT = "minor_participant"
    LOCATION = "location"
    PRIVACY = "privacy"
    SCREEN_RECORDING = "screen_recording"
    SENSITIVE_DATA = "sensitive_data"
    EQUIPMENT = "equipment"
    BACKUP = "backup"
    AUDIO = "audio"
    LIGHTING = "lighting"
    CONTINUITY = "continuity"
    SCHEDULE = "schedule"
    RESOURCE = "resource"
    SAFETY = "safety"
    PLATFORM = "platform"
    MEASUREMENT = "measurement"
    BRAND = "brand"
    CREATOR_BOUNDARY = "creator_boundary"
    ACCESSIBILITY = "accessibility"
    OPERATIONAL = "operational"
    SATURATION = "saturation"
    TREND_DECAY = "trend_decay"
    UNKNOWN = "unknown"


class LifecycleStatus(_StrEnum):
    DRAFT = "draft"
    NEEDS_REVIEW = "needs_review"
    APPROVED = "approved"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    SUPERSEDED = "superseded"
    ARCHIVED = "archived"


class PlatformAdaptationType(_StrEnum):
    SHORTS = "shorts"
    LONGFORM = "longform"
    REELS = "reels"
    CAROUSEL = "carousel"
    STORIES = "stories"
    TIKTOK = "tiktok"
    COMMUNITY_POST = "community_post"
    CUSTOM = "custom"
