"""Enumeraciones del dominio de Content Briefs."""

from __future__ import annotations

from enum import Enum


class _StrEnum(str, Enum):
    def __str__(self) -> str:  # pragma: no cover - conveniencia
        return self.value


class BriefRequestStatus(_StrEnum):
    DRAFT = "draft"
    QUEUED = "queued"
    ASSEMBLING_CONTEXT = "assembling_context"
    VALIDATING_SOURCE = "validating_source"
    MAPPING_OBJECTIVE = "mapping_objective"
    MAPPING_AUDIENCE = "mapping_audience"
    BUILDING_PROMISE = "building_promise"
    BUILDING_ANGLES = "building_angles"
    BUILDING_MESSAGES = "building_messages"
    BUILDING_STRUCTURE = "building_structure"
    MAPPING_PACKAGING = "mapping_packaging"
    VALIDATING_CLAIMS = "validating_claims"
    VALIDATING_REFERENCES = "validating_references"
    EVALUATING_RIGHTS = "evaluating_rights"
    BUILDING_REQUIREMENTS = "building_requirements"
    BUILDING_CHECKLISTS = "building_checklists"
    CALCULATING_READINESS = "calculating_readiness"
    SAVING = "saving"
    COMPLETED = "completed"
    COMPLETED_WITH_WARNINGS = "completed_with_warnings"
    INTERRUPTED = "interrupted"
    CANCELLED = "cancelled"
    FAILED = "failed"


class BriefStatus(_StrEnum):
    DRAFT = "draft"
    ASSEMBLING = "assembling"
    NEEDS_INFORMATION = "needs_information"
    NEEDS_REVIEW = "needs_review"
    APPROVED = "approved"
    READY_FOR_PREPRODUCTION = "ready_for_preproduction"
    PREPRODUCTION_IN_PROGRESS = "preproduction_in_progress"
    BLOCKED = "blocked"
    READY_FOR_PRODUCTION = "ready_for_production"
    IN_PRODUCTION = "in_production"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    SUPERSEDED = "superseded"
    ARCHIVED = "archived"


class BriefType(_StrEnum):
    VIDEO_BRIEF = "video_brief"
    SHORT_VIDEO_BRIEF = "short_video_brief"
    LONGFORM_VIDEO_BRIEF = "longform_video_brief"
    LIVESTREAM_BRIEF = "livestream_brief"
    AUDIO_BRIEF = "audio_brief"
    PODCAST_BRIEF = "podcast_brief"
    IMAGE_POST_BRIEF = "image_post_brief"
    CAROUSEL_BRIEF = "carousel_brief"
    STORY_BRIEF = "story_brief"
    COMMUNITY_POST_BRIEF = "community_post_brief"
    ARTICLE_BRIEF = "article_brief"
    NEWSLETTER_BRIEF = "newsletter_brief"
    REPURPOSE_BRIEF = "repurpose_brief"
    CAMPAIGN_CONTENT_BRIEF = "campaign_content_brief"
    SERIES_EPISODE_BRIEF = "series_episode_brief"
    EXPERIMENT_BRIEF = "experiment_brief"
    RESEARCH_BRIEF = "research_brief"
    PACKAGING_TEST_BRIEF = "packaging_test_brief"
    UNKNOWN = "unknown"


class SectionType(_StrEnum):
    AUDIENCE = "audience"
    PROMISE = "promise"
    ANGLE = "angle"
    MESSAGE = "message"
    STRUCTURE = "structure"
    CLAIMS = "claims"
    PACKAGING = "packaging"
    REFERENCES = "references"
    RIGHTS = "rights"
    ASSETS = "assets"
    PREPRODUCTION = "preproduction"
    CHECKLIST = "checklist"
    READINESS = "readiness"
    CUSTOM = "custom"


class AudienceType(_StrEnum):
    PRIMARY = "primary"
    SECONDARY = "secondary"
    UNKNOWN = "unknown"


class PromiseType(_StrEnum):
    DIRECT = "direct"
    IMPLIED = "implied"
    EDUCATIONAL = "educational"
    ENTERTAINMENT = "entertainment"
    SEARCH = "search"
    EXPERIMENTAL = "experimental"
    UNKNOWN = "unknown"


class AngleType(_StrEnum):
    EDUCATIONAL = "educational"
    ENTERTAINING = "entertaining"
    ANALYTICAL = "analytical"
    EMOTIONAL = "emotional"
    PRACTICAL = "practical"
    CONTROVERSIAL = "controversial"
    MYTH_BUSTING = "myth_busting"
    PROBLEM_SOLUTION = "problem_solution"
    BEFORE_AFTER = "before_after"
    CHALLENGE = "challenge"
    EXPERIMENT = "experiment"
    COMPARISON = "comparison"
    REACTION = "reaction"
    STORY = "story"
    CASE_STUDY = "case_study"
    LIST = "list"
    WALKTHROUGH = "walkthrough"
    BEHIND_THE_SCENES = "behind_the_scenes"
    AUTHORITY = "authority"
    COMMUNITY = "community"
    SEARCH_FOCUSED = "search_focused"
    TREND_ADAPTATION = "trend_adaptation"
    EVERGREEN = "evergreen"
    UNKNOWN = "unknown"


class MessageLevel(_StrEnum):
    CORE = "core"
    SUPPORTING = "supporting"
    PROOF = "proof"
    CONTEXT = "context"
    OBJECTION = "objection"
    CTA = "cta"
    NON_GOAL = "non_goal"
    PROHIBITED = "prohibited"


class HookType(_StrEnum):
    QUESTION = "question"
    CONFLICT = "conflict"
    SURPRISING_FACT = "surprising_fact"
    RESULT_FIRST = "result_first"
    MISTAKE = "mistake"
    CHALLENGE = "challenge"
    CURIOSITY_GAP = "curiosity_gap"
    VISUAL_DEMONSTRATION = "visual_demonstration"
    AUTHORITY = "authority"
    STORY_OPEN = "story_open"
    EMOTIONAL = "emotional"
    DIRECT_PROMISE = "direct_promise"
    CONTRAST = "contrast"
    MYTH = "myth"
    AUDIENCE_IDENTIFICATION = "audience_identification"
    UNKNOWN = "unknown"


class NarrativeOutlineType(_StrEnum):
    HOOK_PROBLEM_SOLUTION = "hook_problem_solution"
    BEFORE_AFTER = "before_after"
    SETUP_CONFLICT_RESOLUTION = "setup_conflict_resolution"
    QUESTION_EXPLANATION_APPLICATION = "question_explanation_application"
    MISTAKE_CORRECTION_PRACTICE = "mistake_correction_practice"
    CLAIM_EVIDENCE_CONCLUSION = "claim_evidence_conclusion"
    LIST_PROGRESSION = "list_progression"
    STORY_LESSON = "story_lesson"
    EXPERIMENT_RESULT_LEARNING = "experiment_result_learning"
    TUTORIAL_STEPS = "tutorial_steps"
    COMPARISON = "comparison"
    CASE_STUDY = "case_study"
    CUSTOM = "custom"


class ClaimType(_StrEnum):
    FACT = "fact"
    INFERENCE = "inference"
    HYPOTHESIS = "hypothesis"
    OPINION = "opinion"
    ESTIMATE = "estimate"
    PROMISE = "promise"
    COMPARATIVE_CLAIM = "comparative_claim"
    PERFORMANCE_CLAIM = "performance_claim"
    CAUSAL_CLAIM = "causal_claim"
    LEGAL_CLAIM = "legal_claim"
    HEALTH_CLAIM = "health_claim"
    FINANCIAL_CLAIM = "financial_claim"
    UNKNOWN = "unknown"


class ClaimVerificationStatus(_StrEnum):
    UNVERIFIED = "unverified"
    VERIFICATION_REQUIRED = "verification_required"
    PARTIALLY_VERIFIED = "partially_verified"
    VERIFIED = "verified"
    CONTRADICTED = "contradicted"
    UNVERIFIABLE = "unverifiable"
    NOT_REQUIRED = "not_required"
    BLOCKED = "blocked"


class CopyingRiskLevel(_StrEnum):
    NONE = "none"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    PROHIBITED = "prohibited"
    UNKNOWN = "unknown"


class RightsType(_StrEnum):
    COPYRIGHT = "copyright"
    TRADEMARK = "trademark"
    MUSIC_LICENSE = "music_license"
    FOOTAGE_LICENSE = "footage_license"
    IMAGE_LICENSE = "image_license"
    VOICE_PERMISSION = "voice_permission"
    PARTICIPANT_RELEASE = "participant_release"
    LOCATION_PERMISSION = "location_permission"
    PRODUCT_PERMISSION = "product_permission"
    LOGO_PERMISSION = "logo_permission"
    CHARACTER_PERMISSION = "character_permission"
    DATA_PERMISSION = "data_permission"
    QUOTE_PERMISSION = "quote_permission"
    UNKNOWN = "unknown"


class RightsStatus(_StrEnum):
    NOT_REQUIRED = "not_required"
    UNKNOWN = "unknown"
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED = "expired"
    RESTRICTED = "restricted"
    BLOCKED = "blocked"


class AssetType(_StrEnum):
    EXISTING_VIDEO = "existing_video"
    EXISTING_AUDIO = "existing_audio"
    EXISTING_IMAGE = "existing_image"
    CREATOR_RECORDING = "creator_recording"
    VOICEOVER = "voiceover"
    MUSIC = "music"
    SOUND_EFFECT = "sound_effect"
    B_ROLL = "b_roll"
    SCREEN_RECORDING = "screen_recording"
    CHART = "chart"
    GRAPHIC = "graphic"
    LOGO = "logo"
    PRODUCT = "product"
    PROP = "prop"
    WARDROBE = "wardrobe"
    LOCATION = "location"
    RELEASE_FORM = "release_form"
    REFERENCE_DOCUMENT = "reference_document"
    DATASET = "dataset"
    THUMBNAIL_ASSET = "thumbnail_asset"
    CAPTION_FILE = "caption_file"
    UNKNOWN = "unknown"


class ProductionRequirementType(_StrEnum):
    RESEARCH = "research"
    FACT_CHECK = "fact_check"
    SCRIPT_DRAFT = "script_draft"
    OUTLINE_REVIEW = "outline_review"
    CREATOR_APPROVAL = "creator_approval"
    BRAND_REVIEW = "brand_review"
    LEGAL_REVIEW = "legal_review"
    RIGHTS_CLEARANCE = "rights_clearance"
    LOCATION = "location"
    PARTICIPANT = "participant"
    EQUIPMENT = "equipment"
    RECORDING = "recording"
    SCREEN_CAPTURE = "screen_capture"
    B_ROLL = "b_roll"
    GRAPHICS = "graphics"
    AUDIO = "audio"
    PACKAGING = "packaging"
    METADATA = "metadata"
    ACCESSIBILITY = "accessibility"
    MEASUREMENT_SETUP = "measurement_setup"
    BACKUP = "backup"
    UNKNOWN = "unknown"


class ReadinessStatus(_StrEnum):
    NOT_STARTED = "not_started"
    INCOMPLETE = "incomplete"
    NEEDS_INFORMATION = "needs_information"
    NEEDS_REVIEW = "needs_review"
    BLOCKED = "blocked"
    CONDITIONALLY_READY = "conditionally_ready"
    READY_FOR_PREPRODUCTION = "ready_for_preproduction"
    PREPRODUCTION_IN_PROGRESS = "preproduction_in_progress"
    READY_FOR_PRODUCTION = "ready_for_production"
    UNKNOWN = "unknown"


class BoundaryType(_StrEnum):
    CREATOR_BOUNDARY = "creator_boundary"
    BRAND_BOUNDARY = "brand_boundary"
    TOPIC_BOUNDARY = "topic_boundary"
    LANGUAGE_BOUNDARY = "language_boundary"
    PRIVACY_BOUNDARY = "privacy_boundary"
    LEGAL_BOUNDARY = "legal_boundary"
    RIGHTS_BOUNDARY = "rights_boundary"
    AUDIENCE_SAFETY_BOUNDARY = "audience_safety_boundary"
    PLATFORM_BOUNDARY = "platform_boundary"
    OPERATIONAL_BOUNDARY = "operational_boundary"
    UNKNOWN = "unknown"


class DependencyType(_StrEnum):
    ROADMAP_ITEM = "roadmap_item"
    RECOMMENDATION = "recommendation"
    EXPERIMENT = "experiment"
    INTERNAL_CONTENT = "internal_content"
    FACT_CHECK = "fact_check"
    RIGHTS = "rights"
    ASSET = "asset"
    RESOURCE = "resource"
    PARTICIPANT = "participant"
    LOCATION = "location"
    EQUIPMENT = "equipment"
    APPROVAL = "approval"
    PLATFORM_ACCESS = "platform_access"
    MEASUREMENT = "measurement"
    CUSTOM = "custom"


class RiskType(_StrEnum):
    EVIDENCE = "evidence"
    CLAIM = "claim"
    MISINFORMATION = "misinformation"
    COPYING = "copying"
    RIGHTS = "rights"
    LEGAL = "legal"
    BRAND = "brand"
    CREATOR_BOUNDARY = "creator_boundary"
    AUDIENCE_MISMATCH = "audience_mismatch"
    PLATFORM_MISMATCH = "platform_mismatch"
    OPERATIONAL = "operational"
    CAPACITY = "capacity"
    RESOURCE = "resource"
    SCHEDULE = "schedule"
    PARTICIPANT = "participant"
    LOCATION = "location"
    EQUIPMENT = "equipment"
    ASSET = "asset"
    MEASUREMENT = "measurement"
    ACCESSIBILITY = "accessibility"
    PRIVACY = "privacy"
    REPUTATION = "reputation"
    SATURATION = "saturation"
    TREND_DECAY = "trend_decay"
    UNKNOWN = "unknown"


class ApprovalGateType(_StrEnum):
    CONCEPT_APPROVAL = "concept_approval"
    OBJECTIVE_APPROVAL = "objective_approval"
    AUDIENCE_APPROVAL = "audience_approval"
    MESSAGE_APPROVAL = "message_approval"
    STRUCTURE_APPROVAL = "structure_approval"
    FACT_CHECK_APPROVAL = "fact_check_approval"
    CREATOR_LANGUAGE_APPROVAL = "creator_language_approval"
    PACKAGING_DIRECTION_APPROVAL = "packaging_direction_approval"
    RIGHTS_APPROVAL = "rights_approval"
    BRAND_APPROVAL = "brand_approval"
    LEGAL_APPROVAL = "legal_approval"
    RESOURCE_APPROVAL = "resource_approval"
    PREPRODUCTION_APPROVAL = "preproduction_approval"
    FINAL_PRODUCTION_READINESS = "final_production_readiness"
    CUSTOM = "custom"


class ReviewDecision(_StrEnum):
    APPROVE = "approve"
    REJECT = "reject"
    DEFER = "defer"
    NEEDS_INFORMATION = "needs_information"
    REQUEST_CHANGES = "request_changes"
    REDUCE_SCOPE = "reduce_scope"
    CHANGE_OBJECTIVE = "change_objective"
    CHANGE_AUDIENCE = "change_audience"
    CHANGE_PLATFORM = "change_platform"
    CHANGE_FORMAT = "change_format"
    CHANGE_ANGLE = "change_angle"
    CHANGE_MESSAGE = "change_message"
    REMOVE_CLAIM = "remove_claim"
    REQUEST_FACT_CHECK = "request_fact_check"
    REPLACE_REFERENCE = "replace_reference"
    REQUEST_RIGHTS_REVIEW = "request_rights_review"
    APPROVE_PREPRODUCTION = "approve_preproduction"
    APPROVE_PRODUCTION_READINESS = "approve_production_readiness"
    BLOCK = "block"
    SUPERSEDE = "supersede"
    ARCHIVE = "archive"

