"""Contratos de persistencia para TikTok."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    TikTokConnection,
    TikTokContentLink,
    TikTokCoverVersion,
    TikTokMetricImport,
    TikTokMetricValue,
    TikTokProfile,
    TikTokRateLimitUsage,
    TikTokRemoteVideo,
    TikTokSyncItem,
    TikTokSyncReport,
    TikTokSyncRun,
    TikTokSyncSchedule,
    TikTokVideoTextVersion,
)


class TikTokIntegrationRepository(Protocol):
    def upsert_connection(self, connection: TikTokConnection) -> TikTokConnection: ...
    def get_connection(self, connection_id: str) -> TikTokConnection | None: ...
    def list_connections(self, creator_id: str) -> list[TikTokConnection]: ...

    def upsert_profile(self, profile: TikTokProfile) -> TikTokProfile: ...
    def get_profile(self, profile_id: str) -> TikTokProfile | None: ...
    def get_profile_by_open_id(self, creator_id: str, open_id: str) -> TikTokProfile | None: ...
    def list_profiles(self, creator_id: str, *, connection_id: str | None = None) -> list[TikTokProfile]: ...

    def upsert_remote_video(self, video: TikTokRemoteVideo) -> TikTokRemoteVideo: ...
    def get_remote_video(self, remote_video_id: str) -> TikTokRemoteVideo | None: ...
    def get_remote_video_by_tiktok_id(self, creator_id: str, tiktok_video_id: str) -> TikTokRemoteVideo | None: ...
    def list_remote_videos(self, creator_id: str, *, profile_id: str | None = None) -> list[TikTokRemoteVideo]: ...

    def upsert_video_text_version(self, version: TikTokVideoTextVersion) -> TikTokVideoTextVersion: ...
    def list_video_text_versions(self, remote_video_id: str) -> list[TikTokVideoTextVersion]: ...

    def upsert_cover_version(self, version: TikTokCoverVersion) -> TikTokCoverVersion: ...
    def list_cover_versions(self, remote_video_id: str) -> list[TikTokCoverVersion]: ...

    def upsert_sync_run(self, run: TikTokSyncRun) -> TikTokSyncRun: ...
    def get_sync_run(self, run_id: str) -> TikTokSyncRun | None: ...
    def list_sync_runs(self, creator_id: str) -> list[TikTokSyncRun]: ...
    def get_latest_sync_run(self, creator_id: str, *, connection_id: str | None = None) -> TikTokSyncRun | None: ...

    def upsert_sync_item(self, item: TikTokSyncItem) -> TikTokSyncItem: ...
    def list_sync_items(self, sync_run_id: str) -> list[TikTokSyncItem]: ...

    def upsert_metric_import(self, metric_import: TikTokMetricImport) -> TikTokMetricImport: ...
    def get_metric_import(self, metric_import_id: str) -> TikTokMetricImport | None: ...
    def list_metric_imports(self, creator_id: str, *, profile_id: str | None = None) -> list[TikTokMetricImport]: ...

    def upsert_metric_value(self, metric_value: TikTokMetricValue) -> TikTokMetricValue: ...
    def list_metric_values(self, metric_import_id: str) -> list[TikTokMetricValue]: ...

    def upsert_content_link(self, link: TikTokContentLink) -> TikTokContentLink: ...
    def get_content_link(self, link_id: str) -> TikTokContentLink | None: ...
    def list_content_links(self, creator_id: str) -> list[TikTokContentLink]: ...

    def upsert_rate_limit_usage(self, usage: TikTokRateLimitUsage) -> TikTokRateLimitUsage: ...
    def list_rate_limit_usage(self, connection_id: str) -> list[TikTokRateLimitUsage]: ...

    def upsert_sync_schedule(self, schedule: TikTokSyncSchedule) -> TikTokSyncSchedule: ...
    def list_sync_schedules(self, creator_id: str, *, connection_id: str | None = None) -> list[TikTokSyncSchedule]: ...

