"""Contrato de persistencia para la consolidacion de integraciones."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    PlatformCapabilitySnapshot,
    PlatformConnectionHealth,
    PlatformConnectionSummary,
    PlatformDataAvailability,
    PlatformIntegrationEvent,
    PlatformManualImportStatus,
    PlatformReport,
    PlatformScheduleRegistryEntry,
    PlatformSyncGroup,
    PlatformSyncGroupItem,
)


class PlatformIntegrationRepository(Protocol):
    def upsert_platform_connection(self, record: PlatformConnectionSummary) -> PlatformConnectionSummary: ...
    def get_platform_connection(self, platform_connection_id: str) -> PlatformConnectionSummary | None: ...
    def list_platform_connections(self, creator_id: str): ...
    def upsert_platform_connection_health(self, record: PlatformConnectionHealth) -> PlatformConnectionHealth: ...
    def list_platform_connection_health(self, creator_id: str): ...
    def upsert_platform_capability_snapshot(self, record: PlatformCapabilitySnapshot) -> PlatformCapabilitySnapshot: ...
    def list_platform_capability_snapshots(self, creator_id: str): ...
    def upsert_platform_data_availability(self, record: PlatformDataAvailability) -> PlatformDataAvailability: ...
    def list_platform_data_availability(self, creator_id: str): ...
    def upsert_platform_sync_group(self, record: PlatformSyncGroup) -> PlatformSyncGroup: ...
    def get_platform_sync_group(self, sync_group_id: str) -> PlatformSyncGroup | None: ...
    def list_platform_sync_groups(self, creator_id: str): ...
    def upsert_platform_sync_group_item(self, record: PlatformSyncGroupItem) -> PlatformSyncGroupItem: ...
    def list_platform_sync_group_items(self, sync_group_id: str): ...
    def upsert_platform_schedule_registry_entry(self, record: PlatformScheduleRegistryEntry) -> PlatformScheduleRegistryEntry: ...
    def list_platform_schedule_registry_entries(self, creator_id: str): ...
    def upsert_platform_manual_import_status(self, record: PlatformManualImportStatus) -> PlatformManualImportStatus: ...
    def list_platform_manual_import_status(self, creator_id: str): ...
    def upsert_platform_integration_event(self, record: PlatformIntegrationEvent) -> PlatformIntegrationEvent: ...
    def list_platform_integration_events(self, creator_id: str): ...
    def upsert_platform_report(self, record: PlatformReport) -> PlatformReport: ...
    def get_platform_report(self, report_id: str) -> PlatformReport | None: ...
    def list_platform_reports(self, creator_id: str): ...
