"""Tipos principales de recomendaciones."""

from __future__ import annotations

from enum import Enum


class RecommendationType(str, Enum):
    TOPIC = "topic_recommendation"
    FORMAT = "format_recommendation"
    SERIES = "series_recommendation"
    PLATFORM = "platform_recommendation"
    TIMING = "timing_recommendation"
    PACKAGING = "packaging_recommendation"
    TITLE_DIRECTION = "title_direction_recommendation"
    THUMBNAIL_DIRECTION = "thumbnail_direction_recommendation"
    HOOK_DIRECTION = "hook_direction_recommendation"
    DURATION = "duration_recommendation"
    CONTENT_REPURPOSE = "content_repurpose_recommendation"
    CROSS_PLATFORM_ADAPTATION = "cross_platform_adaptation_recommendation"
    AUDIENCE = "audience_recommendation"
    DISTRIBUTION = "distribution_recommendation"
    EXPERIMENT = "experiment_recommendation"
    CONTENT_GAP = "content_gap_recommendation"
    REVIVAL = "revival_recommendation"
    DIFFERENTIATION = "differentiation_recommendation"
    RISK_REDUCTION = "risk_reduction_recommendation"
    RESEARCH = "research_recommendation"
    DO_NOT_PURSUE = "do_not_pursue_recommendation"


class ObjectiveType(str, Enum):
    AUDIENCE_GROWTH = "audience_growth"
    AWARENESS = "awareness"
    REACH = "reach"
    DISCOVERY = "discovery"
    VIEWS = "views"
    WATCH_TIME = "watch_time"
    RETENTION = "retention"
    COMPLETION = "completion"
    ENGAGEMENT = "engagement"
    SAVES = "saves"
    SHARES = "shares"
    COMMENTS = "comments"
    SUBSCRIBER_GROWTH = "subscriber_growth"
    FOLLOWER_GROWTH = "follower_growth"
    RETURNING_AUDIENCE = "returning_audience"
    AUDIENCE_DEPTH = "audience_depth"
    SEARCH_DISCOVERY = "search_discovery"
    PLATFORM_CONVERSION = "platform_conversion"
    LONGFORM_CONVERSION = "longform_conversion"
    SHORTFORM_CONVERSION = "shortform_conversion"
    CONTENT_LEARNING = "content_learning"
    PACKAGING_LEARNING = "packaging_learning"
    MARKET_VALIDATION = "market_validation"
    AUDIENCE_VALIDATION = "audience_validation"
    CREATOR_POSITIONING = "creator_positioning"
    BRAND_CONSISTENCY = "brand_consistency"
    OPERATIONAL_EFFICIENCY = "operational_efficiency"
    UNKNOWN = "unknown"


class PriorityLevel(str, Enum):
    CRITICAL = "critical"
    VERY_HIGH = "very_high"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    VERY_LOW = "very_low"
    BLOCKED = "blocked"
    UNKNOWN = "unknown"


class LifecycleStage(str, Enum):
    EMERGING = "emerging"
    ACCELERATING = "accelerating"
    GROWING = "growing"
    ESTABLISHED = "established"
    SATURATED = "saturated"
    DECLINING = "declining"
    REVIVING = "reviving"
    SEASONAL = "seasonal"
    VOLATILE = "volatile"
    UNCLEAR = "unclear"


class ReviewDecision(str, Enum):
    APPROVE = "approve"
    REJECT = "reject"
    DEFER = "defer"
    NEEDS_MORE_DATA = "needs_more_data"
    REQUEST_ALTERNATIVE = "request_alternative"
    REDUCE_SCOPE = "reduce_scope"
    CHANGE_PLATFORM = "change_platform"
    CHANGE_OBJECTIVE = "change_objective"
    EDIT_CONSTRAINTS = "edit_constraints"
    CONVERT_TO_EXPERIMENT = "convert_to_experiment"
    MARK_EXECUTED = "mark_executed"
    MARK_INCONCLUSIVE = "mark_inconclusive"
    ARCHIVE = "archive"


class FeedbackType(str, Enum):
    USEFUL = "useful"
    NOT_USEFUL = "not_useful"
    TOO_GENERIC = "too_generic"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    WRONG_CREATOR_FIT = "wrong_creator_fit"
    WRONG_AUDIENCE_FIT = "wrong_audience_fit"
    WRONG_PLATFORM = "wrong_platform"
    TOO_RISKY = "too_risky"
    TOO_EXPENSIVE = "too_expensive"
    TOO_COMPLEX = "too_complex"
    STALE = "stale"
    DUPLICATE = "duplicate"
    ALREADY_TRIED = "already_tried"
    CONFLICTS_WITH_BRAND = "conflicts_with_brand"
    GOOD_BUT_NOT_NOW = "good_but_not_now"
    ACCEPTED = "accepted"
