"""Contratos de persistencia para Creator Memory."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    CreatorExample,
    CreatorLimit,
    CreatorMemoryFeedback,
    CreatorProfile,
    CreatorProfileSnapshot,
    CreatorStyleRule,
    CreatorStyleRuleReview,
    CreatorTrait,
    CreatorTraitEvidence,
    CreatorVocabulary,
)
from .memory_types import CreatorMemoryRetrievalResult, CreatorProfileSnapshotComparison


class CreatorMemoryRepository(Protocol):
    def get_profile(self, creator_id: str) -> CreatorProfile | None: ...

    def upsert_profile(self, profile: CreatorProfile) -> CreatorProfile: ...

    def list_traits(self, creator_id: str) -> list[CreatorTrait]: ...

    def get_trait(self, trait_id: str) -> CreatorTrait | None: ...

    def upsert_trait(self, trait: CreatorTrait) -> CreatorTrait: ...

    def archive_trait(self, trait_id: str) -> CreatorTrait | None: ...

    def list_trait_evidence(self, trait_id: str) -> list[CreatorTraitEvidence]: ...

    def upsert_trait_evidence(self, evidence: CreatorTraitEvidence) -> CreatorTraitEvidence: ...

    def list_examples(self, creator_id: str) -> list[CreatorExample]: ...

    def get_example(self, example_id: str) -> CreatorExample | None: ...

    def upsert_example(self, example: CreatorExample) -> CreatorExample: ...

    def review_example(self, example_id: str, approval_status: str, approval_reason: str | None) -> CreatorExample | None: ...

    def list_vocabulary(self, creator_id: str) -> list[CreatorVocabulary]: ...

    def upsert_vocabulary(self, vocabulary: CreatorVocabulary) -> CreatorVocabulary: ...

    def list_style_rules(self, creator_id: str) -> list[CreatorStyleRule]: ...

    def get_style_rule(self, rule_id: str) -> CreatorStyleRule | None: ...

    def upsert_style_rule(self, rule: CreatorStyleRule) -> CreatorStyleRule: ...

    def review_style_rule(self, review: CreatorStyleRuleReview) -> CreatorStyleRuleReview: ...

    def list_style_rule_reviews(self, rule_id: str) -> list[CreatorStyleRuleReview]: ...

    def list_limits(self, creator_id: str) -> list[CreatorLimit]: ...

    def upsert_limit(self, limit: CreatorLimit) -> CreatorLimit: ...

    def list_profile_snapshots(self, creator_id: str) -> list[CreatorProfileSnapshot]: ...

    def upsert_profile_snapshot(self, snapshot: CreatorProfileSnapshot) -> CreatorProfileSnapshot: ...

    def get_profile_snapshot(self, snapshot_id: str) -> CreatorProfileSnapshot | None: ...

    def list_feedback(self, creator_id: str) -> list[CreatorMemoryFeedback]: ...

    def upsert_feedback(self, feedback: CreatorMemoryFeedback) -> CreatorMemoryFeedback: ...

    def retrieve(self, creator_id: str, filters: dict[str, object]) -> list[CreatorMemoryRetrievalResult]: ...

    def compare_snapshots(self, creator_id: str, base_snapshot_id: str, compare_snapshot_id: str) -> CreatorProfileSnapshotComparison: ...

