"""Contrato de persistencia para la integracion YouTube."""

from __future__ import annotations

from typing import Protocol

from .entities import (
    YouTubeChannel,
    YouTubeConnection,
    YouTubeContentLink,
    YouTubeMetricImport,
    YouTubeMetricValue,
    YouTubeQuotaUsage,
    YouTubeRemoteVideo,
    YouTubeSyncItem,
    YouTubeSyncReport,
    YouTubeSyncRun,
    YouTubeSyncSchedule,
    YouTubeVideoThumbnail,
)


class YouTubeIntegrationRepository(Protocol):
    def upsert_connection(self, connection: YouTubeConnection) -> YouTubeConnection: ...
    def get_connection(self, connection_id: str) -> YouTubeConnection | None: ...
    def get_connection_by_credential_reference(self, credential_reference: str) -> YouTubeConnection | None: ...
    def list_connections(self, creator_id: str): ...
    def upsert_channel(self, channel: YouTubeChannel) -> YouTubeChannel: ...
    def get_channel(self, channel_id: str) -> YouTubeChannel | None: ...
    def list_channels(self, creator_id: str): ...
    def upsert_remote_video(self, remote_video: YouTubeRemoteVideo) -> YouTubeRemoteVideo: ...
    def get_remote_video(self, remote_video_id: str) -> YouTubeRemoteVideo | None: ...
    def get_remote_video_by_youtube_id(self, youtube_video_id: str, *, creator_id: str | None = None) -> YouTubeRemoteVideo | None: ...
    def list_remote_videos(self, channel_id: str): ...
    def upsert_video_thumbnail(self, thumbnail: YouTubeVideoThumbnail) -> YouTubeVideoThumbnail: ...
    def list_video_thumbnails(self, remote_video_id: str): ...
    def upsert_sync_run(self, sync_run: YouTubeSyncRun) -> YouTubeSyncRun: ...
    def get_sync_run(self, run_id: str) -> YouTubeSyncRun | None: ...
    def list_sync_runs(self, creator_id: str): ...
    def upsert_sync_item(self, sync_item: YouTubeSyncItem) -> YouTubeSyncItem: ...
    def list_sync_items(self, sync_run_id: str): ...
    def upsert_metric_import(self, metric_import: YouTubeMetricImport) -> YouTubeMetricImport: ...
    def list_metric_imports(self, creator_id: str): ...
    def upsert_metric_value(self, metric_value: YouTubeMetricValue) -> YouTubeMetricValue: ...
    def list_metric_values(self, metric_import_id: str): ...
    def upsert_content_link(self, content_link: YouTubeContentLink) -> YouTubeContentLink: ...
    def list_content_links(self, creator_id: str): ...
    def get_content_link_by_remote_video(self, remote_video_id: str) -> YouTubeContentLink | None: ...
    def upsert_quota_usage(self, quota_usage: YouTubeQuotaUsage) -> YouTubeQuotaUsage: ...
    def list_quota_usage(self, connection_id: str): ...
    def upsert_sync_schedule(self, schedule: YouTubeSyncSchedule) -> YouTubeSyncSchedule: ...
    def list_sync_schedules(self, creator_id: str): ...

